/*
   SPDX-FileCopyrightText: 2019-2025 Laurent Montel <montel@kde.org>

   SPDX-License-Identifier: LGPL-2.0-or-later
*/

#pragma once

#include "textemoticonscore_export.h"
#include "unicodeemoticon.h"
#include <QList>
namespace TextEmoticonsCore
{
/**
 * @brief The UnicodeEmoticonParser class
 * @author Laurent Montel <montel@kde.org>
 */
class TEXTEMOTICONSCORE_EXPORT UnicodeEmoticonParser
{
public:
    UnicodeEmoticonParser();
    ~UnicodeEmoticonParser();

    /**
     * @brief Parses a dict file that contains emoji data. This kind of file is only generated by KTextAddons.
     */
    [[nodiscard]] QList<UnicodeEmoticon> parse(const QString &path) const;
};
}
