# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'third-party/qtkeychain': '@latest'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/sonnet': '@latest-kf6'
    'frameworks/syntax-highlighting': '@latest-kf6'
    'frameworks/breeze-icons': '@latest-kf6'


- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/karchive': '@latest'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/sonnet': '@stable'
    'frameworks/syntax-highlighting': '@stable'
    'frameworks/breeze-icons': '@stable'
      
