# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'third-party/qtkeychain': '@latest'

- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcolorscheme': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/sonnet': '@latest-kf6'
    'frameworks/syntax-highlighting': '@latest-kf6'
    'frameworks/breeze-icons': '@latest-kf6'


Options:
  cmake-options: "-DDISABLE_AUTOTEST_BROKEN_CI=TRUE"
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
