# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on': ['@all']
    'require':
      'third-party/qtkeychain': '@latest'
  - 'on': ['Linux']
    'require':
      'frameworks/extra-cmake-modules': 'Frameworks/6.24'
      'frameworks/ki18n': 'Frameworks/6.24'
      'frameworks/kconfig': 'Frameworks/6.24'
      'frameworks/kcolorscheme': 'Frameworks/6.24'
      'frameworks/karchive': 'Frameworks/6.24'
      'frameworks/kcoreaddons': 'Frameworks/6.24'
      'frameworks/kio': 'Frameworks/6.24'
      'frameworks/sonnet': 'Frameworks/6.24'
      'frameworks/syntax-highlighting': 'Frameworks/6.24'
      'frameworks/breeze-icons': 'Frameworks/6.24'
      'frameworks/ktextwidgets': 'Frameworks/6.24'
      'frameworks/kitemviews': 'Frameworks/6.24'
      'frameworks/kiconthemes': 'Frameworks/6.24'
      'frameworks/kservice': 'Frameworks/6.24'

Options:
  cmake-options: "-DDISABLE_AUTOTEST_BROKEN_CI=TRUE"
  require-passing-tests-on: ['Linux']
  tests-run-in-parallel: True
