# SPDX-FileCopyrightText: Montel Laurent <montel@kde.org>
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "ktextaddons"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/ktextaddons"

[[annotations]]
path = ["textautocorrection/core/autotests/data/**", "textgrammarcheck/grammalecte/autotests/data/**.json", "textgrammarcheck/languagetool/autotests/data/**.json", ".gitattributes", "textemoticons/core/data/emoji.json", "textemoticons/widgets/tests/gif1.gif", "texttranslator/translator/plugins/bergamot/autotests/data/translator/**.json", "texttranslator/translator/plugins/bergamot/autotests/data/modellanguages/**.json", "texttranslator/translator/plugins/bergamot/autotests/data/test-stored-languages/test2/enet1/model_info.json", "texttranslator/translator/plugins/bergamot/autotests/data/test-stored-languages/test2/enet2/model_info.json", "texttranslator/translator/plugins/bergamot/autotests/data/test-stored-languages/test2/enet3/model_info.json", "textspeechtotext/speechtotext/plugins/vosk/autotests/data/info/empty.json", "textspeechtotext/speechtotext/plugins/vosk/autotests/data/info/test1.json", "textspeechtotext/speechtotext/plugins/vosk/autotests/data/modellanguages/empty.json", "textspeechtotext/speechtotext/plugins/vosk/autotests/data/modellanguages/invalid.json", "textspeechtotext/speechtotext/plugins/vosk/autotests/data/modellanguages/model-list.json", "cmake/COPYING-CMAKE-SCRIPTS"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "docs/pics/**.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 KDE Community"
SPDX-License-Identifier = "CC-BY-SA-4.0"
