/*
  SPDX-FileCopyrightText: 2025 Laurent Montel <montel@kde.org>

  SPDX-License-Identifier: GPL-2.0-or-later
*/

#pragma once
#include "textautogeneratetext_export.h"
#include <QDialog>
namespace TextAutogenerateText
{
class TextAutogenerateStackWidget;
/**
 * @brief The TextAutogenerateDialog class
 * @author Laurent Montel <montel@kde.org>
 */
class TEXTAUTOGENERATETEXT_EXPORT TextAutogenerateDialog : public QDialog
{
    Q_OBJECT
public:
    explicit TextAutogenerateDialog(QWidget *parent = nullptr);
    ~TextAutogenerateDialog() override;

    void ask(const QString &str);

private:
    TEXTAUTOGENERATETEXT_NO_EXPORT void readConfig();
    TEXTAUTOGENERATETEXT_NO_EXPORT void writeConfig();
    TextAutogenerateStackWidget *const mTextAutogenerateWidget;
};
}
