/*
   SPDX-FileCopyrightText: 2025-2026 Laurent Montel <montel@kde.org>

   SPDX-License-Identifier: LGPL-2.0-or-later
*/
#include "textautogenerateattachmentdelegatehelperfile.h"
#include "widgets/common/textautogeneratetextopenfilejob.h"
#include "widgets/view/textautogeneratedelegateutils.h"
#include <KIconLoader>
#include <QMimeDatabase>
#include <QPainter>
#include <QPixmap>
#include <TextAutoGenerateText/TextAutoGenerateAttachment>
#include <TextAutoGenerateText/TextAutoGenerateMessage>
#include <TextAutoGenerateText/TextAutoGenerateMessagesModel>

using namespace TextAutoGenerateText;
using namespace Qt::Literals::StringLiterals;
TextAutoGenerateAttachmentDelegateHelperFile::TextAutoGenerateAttachmentDelegateHelperFile(TextAutoGenerateText::TextAutoGenerateManager *manager,
                                                                                           QObject *parent)
    : TextAutoGenerateAttachmentDelegateHelperBase{manager, parent}
{
}

TextAutoGenerateAttachmentDelegateHelperFile::~TextAutoGenerateAttachmentDelegateHelperFile() = default;

// Icon + text
void TextAutoGenerateAttachmentDelegateHelperFile::draw(const TextAutoGenerateText::TextAutoGenerateAttachment &msgAttach,
                                                        QPainter *painter,
                                                        QRect attachmentsRect,
                                                        const QModelIndex &index,
                                                        const QStyleOptionViewItem &option) const
{
    const FileLayout layout = doLayout(msgAttach, option, attachmentsRect.width());
    const TextAutoGenerateMessage::Sender sender = index.data(TextAutoGenerateMessagesModel::SenderRole).value<TextAutoGenerateMessage::Sender>();
    const bool isUser = (sender == TextAutoGenerateMessage::Sender::User);
    const int indent = isUser ? TextAutoGenerateDelegateUtils::marginText() : TextAutoGenerateDelegateUtils::leftLLMIndent();

    // Draw inside attachmentsRect: the delegate stacks one rect per attachment from top to bottom,
    // so drawing from the bottom edge would paint over the next attachment (and outside the message).
    const int left = attachmentsRect.left() + indent;
    const int rowHeight = qMax(attachmentsRect.height(), layout.pixmap.height());
    painter->drawPixmap(left, attachmentsRect.top() + (rowHeight - layout.pixmap.height()) / 2, layout.pixmap);

    const QFontMetrics fontMetrics(painter->font());
    const int baseLine = attachmentsRect.top() + (rowHeight - fontMetrics.height()) / 2 + fontMetrics.ascent();
    painter->drawText(left + layout.pixmap.width() + TextAutoGenerateDelegateUtils::spacingText(), baseLine, layout.name);
}

QSize TextAutoGenerateAttachmentDelegateHelperFile::sizeHint(const TextAutoGenerateText::TextAutoGenerateAttachment &msgAttach,
                                                             [[maybe_unused]] const QModelIndex &index,
                                                             int maxWidth,
                                                             const QStyleOptionViewItem &option) const
{
    const FileLayout layout = doLayout(msgAttach, option, maxWidth);

    // Same content as draw(): icon + spacing + name, the row is as tall as the tallest of the two.
    return {layout.pixmap.width() + TextAutoGenerateDelegateUtils::spacingText() + layout.nameSize.width(),
            qMax(layout.pixmap.height(), layout.nameSize.height())};
}

bool TextAutoGenerateAttachmentDelegateHelperFile::handleMouseEvent(const TextAutoGenerateAttachment &msgAttach,
                                                                    QMouseEvent *mouseEvent,
                                                                    QRect attachmentsRect,
                                                                    const QStyleOptionViewItem &option,
                                                                    const QModelIndex &index)
{
    const QEvent::Type eventType = mouseEvent->type();
    switch (eventType) {
    case QEvent::MouseButtonRelease: {
        // const FileLayout layout = doLayout(msgAttach, option, attachmentsRect.width());
        if (const QPoint pos = mouseEvent->pos(); attachmentsRect.contains(pos)) {
            if (const auto attachmentId = msgAttach.attachmentId(); !attachmentId.isEmpty()) {
                qDebug() << " Click on file " << msgAttach;
                handleDownloadClicked(const_cast<QWidget *>(option.widget), attachmentId);
                return true;
            }
            qDebug() << " Click on file " << msgAttach;
        }
        break;
    }
    default:
        break;
    }
    return TextAutoGenerateAttachmentDelegateHelperBase::handleMouseEvent(msgAttach, mouseEvent, attachmentsRect, option, index);
}

QPoint TextAutoGenerateAttachmentDelegateHelperFile::adaptMousePosition(const QPoint &pos,
                                                                        const TextAutoGenerateAttachment &msgAttach,
                                                                        QRect attachmentsRect,
                                                                        const QStyleOptionViewItem &option)
{
    // TODO
    return pos;
}

TextAutoGenerateAttachmentDelegateHelperFile::FileLayout
TextAutoGenerateAttachmentDelegateHelperFile::doLayout(const TextAutoGenerateText::TextAutoGenerateAttachment &msgAttach,
                                                       const QStyleOptionViewItem &option,
                                                       [[maybe_unused]] int attachmentsWidth) const
{
    FileLayout layout;
    layout.mimetype = msgAttach.mimeType();
    layout.name = msgAttach.name();
    // TODO cache it.
    const QMimeDatabase db;
    const QMimeType mimeType = db.mimeTypeForName(QString::fromLatin1(layout.mimetype));
    const QString mimeTypeIconName = mimeType.iconName();
    // qDebug() << " mimeTypeIconName " << mimeTypeIconName;
    // qDebug() << " layout.name " << layout.name;
    const QString mimeTypeIconPath = KIconLoader::global()->iconPath(mimeTypeIconName, KIconLoader::Small);
    const QPixmap pix(mimeTypeIconPath);

    // qDebug() << " mimeTypeIconPath " << mimeTypeIconPath;
    const QPixmap scaledPixmap = pix.scaled(18, 18, Qt::KeepAspectRatio, Qt::SmoothTransformation);
    layout.pixmap = scaledPixmap;

    layout.nameSize = option.fontMetrics.size(Qt::TextSingleLine, layout.name);
    return layout;
}

void TextAutoGenerateAttachmentDelegateHelperFile::handleDownloadClicked(QWidget *widget, const QByteArray &attachmentId)
{
    auto job = new TextAutoGenerateText::TextAutoGenerateTextOpenFileJob(mManager, this);
    job->setAttachmentId(attachmentId);
    job->setParentWidget(widget);
    job->start();
}

#include "moc_textautogenerateattachmentdelegatehelperfile.cpp"
