/*
  SPDX-FileCopyrightText: 2025 Laurent Montel <montel@kde.org>

  SPDX-License-Identifier: GPL-2.0-or-later
*/
#pragma once
#include <QAbstractTextDocumentLayout>
#include <QString>
#include <QStyleOptionViewItem>
class QTextDocument;
class QPoint;
namespace TextAutogenerateText
{
class TextAutogenerateListViewTextSelection;
namespace TextAutogenerateDelegateUtils
{
[[nodiscard]] bool generateToolTip(const QTextDocument *doc, const QPoint &pos, QString &formattedTooltip);

void generateToolTip(const QString &toolTip, const QString &href, QString &formattedTooltip);

[[nodiscard]] QList<QAbstractTextDocumentLayout::Selection>
selection(TextAutogenerateListViewTextSelection *selection, QTextDocument *doc, const QModelIndex &index, const QStyleOptionViewItem &option);
}
}
