/*
  SPDX-FileCopyrightText: 2025 Laurent Montel <montel@kde.org>

  SPDX-License-Identifier: GPL-2.0-or-later
*/

#include "textautogeneratedialogtest.h"
#include <QTest>
QTEST_MAIN(TextAutogenerateDialogTest)

TextAutogenerateDialogTest::TextAutogenerateDialogTest(QObject *parent)
    : QObject{parent}
{
}

void TextAutogenerateDialogTest::shouldHaveDefaultValues()
{
    // TODO
}

#include "moc_textautogeneratedialogtest.cpp"
